// List of industry sectors for dropdowns
export const INDUSTRY_SECTORS = [
  'Asset Management & Investments',
  'Auditing & Financial Advisory',
  'Auto Spare Parts Distributors',
  'Auto Spare Parts Trading',
  'Automotive Dealerships',
  'Automotive Services & Maintenance',
  'Banking & Financial Services',
  'Building Materials Trading',
  'CCTV & Alarm Systems',
  'Cash Transfer Services',
  'Civil Construction',
  'Cleaning Equipment Supply',
  'Communication & IT Systems',
  'Conglomerate (Multi-sector)',
  'Construction Materials',
  'Consulting Services',
  'Digital Production & Printers',
  'Drain & Sewage Cleaning',
  'EPC (Engineering, Procurement & Construction)',
  'Educational Institutions',
  'Electrical Supplies',
  'Electro Mechanical Contracting',
  'F&B – Distribution & Services',
  'Finance & Accounting Services',
  'Food & Beverage Manufacturing',
  'Food Distribution',
  'Foodstuff Trading',
  'Garments & Footwear',
  'General Contracting',
  'General Trading',
  'Gift Items',
  'Guarding & Patrolling Services',
  'HVAC Supplies',
  'Heavy Equipment Leasing & Rental',
  'Hypermarket / Department Stores',
  'IT Infrastructure',
  'Insurance & Investment Services',
  'Interior Designing & Turnkey Works',
  'Investment Banking & Brokerage',
  'Investment Holding Companies',
  'Janitorial & Housekeeping',
  'Legal Services',
  'Life Insurance & Health Services',
  'Light Manufacturing',
  'Management Consulting / Advisory',
  'Marble & Granite',
  'Media & Digital Marketing',
  'Medical & Scientific Equipment Trading',
  'Medical Equipment Supply',
  'Money Exchange Services',
  'Oil & Gas',
  'Online Learning Platforms',
  'Power Transmission & Distribution',
  'Printing & Packaging',
  'Real Estate Advisory',
  'Restaurants & Catering Services',
  'Retail – Clothing, Shoes, Accessories',
  'Road Sweeping & Refuse Collection',
  'Scientific Equipment',
  'Security & Surveillance Systems',
  'Shipping & Logistics',
  'Software & App Development',
  'Software Engineering',
  'Steel & Building Materials',
  'Sunrise Restaurant & Catering',
  'Tax Compliance Services',
  'Tea Boy & Messenger Services',
  'Technology Solutions Provider',
  'Telecommunications',
  'Textile Manufacturing',
  'Trademark & Patent Services',
  'Transport Services',
  'Travel & Tourism',
  'Tyres & Automotive Accessories',
  'Tyres & Spare Parts Trading',
  'Uniforms & Clothing Accessories',
  'Utility Contracting',
  'Vocational Training Centers',
  'Warehousing Solutions',
  'Waste Removal Services',
  'Woodwork Joinery',
  'Others',
]; 